### ISSUE TITLE
必须单独安装 tdesign-vue-next 才能获得类型提示

### ISSUE THREAD

**Issue by Aalivexy** [TDesignOteam/tdesign-nuxt#17]
只安装 `@tdesign-vue-next/nuxt` 的话会发现类型提示缺失，但组件可以正常使用：

![image](https://github.com/user-attachments/assets/cdac74e4-aef6-4532-b4f7-c9d09a0a91dc)

安装 `tdesign-vue-next` 后正常：

![image](https://github.com/user-attachments/assets/5cbec47d-3124-4330-a496-c444bdfc8ab2)

是否可以不安装 `tdesign-vue-next` 并且获得类型提示？或者是否应该在 README 中注明需要添加 `tdesign-vue-next` 包？

包管理器：pnpm@9.7.0
tdesign-nuxt 版本：0.1.3

**Comment by liweijie0812** [comment]
🌹，已补充到README
