### ISSUE TITLE
缺少 tabs 组件

### ISSUE THREAD

**Issue by woodcoal** [TDesignOteam/tdesign-nuxt#3]
默认未添加 Tabs 组件

**Comment by woodcoal** [comment]
检查发现实际缺少 Tabs 与 Steps，处理办法：

`src/config/components.ts` 中添加以下代码
```
  steps:["Steps", "StepItem"],
  tabs:["Tabs", "TabPanel"],
```

![image](https://github.com/TDesignOteam/tdesign-nuxt/assets/70026047/1d80f27e-9464-4dc3-bac2-83c5f8d9ba40)

**Comment by uyarn** [comment]
PR is welcome
