### ISSUE TITLE
使用此库，如何使theme继续起作用？

### ISSUE THREAD

**Issue by yuzh2001** [TDesignOteam/tdesign-nuxt#6]
在官网上调整theme下载的css，如果直接在app.vue里import，nuxt模组动态添加的样式会覆盖掉app.vue里的theme

复现：
(in app.vue)
import "theme.css"

(in other pages)
try use any tdesign components. theme won't apply

**Comment by uyarn** [comment]
@yuzh2001 有道理 如果这种情况会被覆盖 我们再提供一个API importStyle 关闭的情况下就不自动引入默认的theme了

**Comment by yuzh2001** [comment]
支持。
不然只要有“覆盖样式”的需求，就很难办hhh

**Comment by uyarn** [comment]
@yuzh2001 麻烦使用这个版本 `@tdesign-vue-next/nuxt@0.1.2` 使用这个版本 并关闭`importVariables`
 ```js
 modules:['@tdesign-vue-next/nuxt'],
 tdesign: {
    importVariables: false
 },
````
