### ISSUE TITLE
auto import plugin conflicts with customising theme

### ISSUE THREAD

**Issue by yuzh2001** [TDesignOteam/tdesign-nuxt#8]
发现在0.1.2中依然存在问题。花了一点时间debug，问题出现在了对plugin的载入上。当plugin被读取的时候，实际上又引用了一次tdesign-vue-next，这导致index.css被引入，覆盖了theme.css。

最小复现：

(app.vue)
```vue
<template>
  <div>
    <NuxtLayout>
      <Head>
        <Style> [type='text'] { padding: 0 !important; } </Style>
      </Head>
      <NuxtPage />
    </NuxtLayout>
  </div>
</template>

<script>
import '~/assets/theme.css'
</script>
```

(/pages/index.vue)
```vue
<template>
  <div>
    <TButton>hello?</TButton>
  </div>
</template>

<script lang="ts" setup>
MessagePlugin.success('保存成功');
</script>

<style>

</style>
```

把MessagePlugin这一行注释掉就不会出现问题了。

---

## 解决

写了一段非常烂但是有效的代码（我不太了解nuxt module的语法，理解思路即可）

```js
// in resolver.ts
const resolveTheme = async (options) => {
  const nuxt = useNuxt();
  const stylePath = '../../../../../..'+options.themePath;
  const tdesignGlobalStyle = await tryResolveModule("tdesign-vue-next/package.json").then((tdLocation) => tdLocation ? join(tdLocation, stylePath) : Promise.reject("Unable to resolve tdesign-vue-next Global Style. Is it installed?"));
  nuxt.options.css.push(tdesignGlobalStyle);
  console.log("\u{1F680} global?");
  console.log(tdesignGlobalStyle);
}

// in modules.ts
...
    themePath: void 0
  },
  setup(options, nuxt) {
  ...
    options.themePath && resolveTheme(options);
  }
});
...

// nuxt.config.ts


  tdesign: {
    importVariables: true,
    themePath: '/assets/css/theme.css',
  },


```

是很蠢的代码，因为path直接疯狂".."循环了。

不过我想应该能理解我的意思。

期待修复~辛苦啦

**Comment by yuzh2001** [comment]
这个解决方法貌似很蠢…可能需要你们研究一下了orz貌似和nuxt如何加载importsources有关

**Comment by yuzh2001** [comment]
update: 可以通过在使用plugin的页面手动引入theme解决以上问题。

不过这样使用plugin时，依然会全量引入全部的tdesign。

**Comment by uyarn** [comment]
我们看下 👀

**Comment by uyarn** [comment]
这个不能这样解决，我们需要的是在规则里解决。我们需要改成统一从plugin具体所在目录export，但是现在部分组件的export 不太统一，所以我们需要同时优化组件库，再发个版本，预计下周可以发布。目前来说，你可以通过手动import plugin来暂时规避问题，即
nuxt.config.ts
```
tdesign: {
   plugins: []
}
```
然后在具体使用的地方 如MessagePlugin 暂时手动引入下
`import { default as MessagePlugin } from 'tdesign-vue-next/es/message/plugin'`
然后来使用

**Comment by liweijie0812** [comment]
![image](https://github.com/TDesignOteam/tdesign-nuxt/assets/10710889/33908d45-db69-4a66-a0e7-e77727da342d)
https://github.com/TDesignOteam/tdesign-nuxt/pull/9

**Comment by uyarn** [comment]
try @tdesign-vue-next/nuxt@0.1.3 @yuzh2001

**Comment by yuzh2001** [comment]
Problem solved. Thanks.
